services:
    server:
        build:
            context: .
            dockerfile: ./app/server/Dockerfile
        ports:
            - "3300:3300"
            - "9229:9229"
        volumes:
            - ./app/server:/app/server
            - /app/server/node_modules
            - ./types:/types
    client:
        build:
            context: .
            dockerfile: ./app/client/Dockerfile
        ports:
            - "3000:3000"
        volumes:
            - ./app/client:/app/client
            - /app/client/node_modules
            - ./types:/types
        depends_on:
            - server
        environment:
            - DEV
            - PORT
