services:
    server:
        build: ./app/server
        ports:
            - "3300:3300"
            - "9229:9229"
        volumes:
            - "./app/server:/app"

    client:
        build: ./app/client
        ports:
            - "3000:3000"
        volumes:
            - "./app/client:/app"
            - "/app/node_modules"
        depends_on:
            - server
